---
- name: Configure nginx on lab server
  hosts: lab
  become: true
  gather_facts: true

  tasks:

    - name: Fail if operating system in not Debian
      ansible.builtin.fail:
        msg: "This plabook currently supports Debian only"
      when: ansible_distribution != "Debian"

    - name: Ensure DevOps Lab directories exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ devops_lab_directories }}"

    - name: Ensure Nginx package is installed
      ansible.builtin.apt:
        name: "{{ nginx_package_name }}"
        state: present
        update_cache: true

    - name: Ensure DevOps Lab documents root exists
      ansible.builtin.file:
        path: /var/www/devops-lab
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Deploy DevOps Lab index page
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: /var/www/devops-lab/index.html
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Deploy Nginx virtual hosts
      ansible.builtin.template:
        src: ../templates/devops-lab.conf.j2
        dest: /etc/nginx/sites-available/devops-lab.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reload Nginx

    - name: Enable DevOps Lab virtual host
      ansible.builtin.file:
        src: /etc/nginx/sites-available/devops-lab.conf
        dest: /etc/nginx/sites-enabled/devops-lab.conf
        state: link
      notify: Reload Nginx

    - name: Disable default Nginx virtual host
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

    - name: Validate Nginx
      ansible.builtin.command:
        cmd: nginx -t
      changed_when: false

    - name: Ensure Nginx service is enabled and started
      ansible.builtin.service:
        name: "{{ nginx_service_name }}"
        state: started
        enabled: true

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: "{{ nginx_service_name }}"
        state: reloaded