---
nginx_package_name: nginx

nginx_service_name: nginx

nginx_listen_port: 80

nginx_server_name: _

devops_lab_environment: prod

devops_lab_page_title: DevOps Automation Lab

base_packages:
  - curl
  - wget
  - git
  - htop
  - tree
  - lsof

devops_lab_directories:
  - path: /var/local/devops-lab
    owner: root
    group: root
    mode: "0755"

  - path: /var/log/devops-lab
    owner: root
    group: root
    mode: "0755"    