---
nginx_package_name: nginx
nginx_service_name: nginx
nginx_listen_port: 80
nginx_server_name: _

devops_lab_page_title: DevOps Lab
devops_lab_environment: lab
devops_lab_host_description: Ansible-managed host